const now = Date.now()
const iso = (daysAgo, h = 10) => new Date(now - daysAgo * 86400000 - (23 - h) * 3600000).toISOString()

export const demoProducts = [
  { id: 'prod_1001', title: 'Hybrid Cotton Seeds BG-II', vernacularTitle: 'हायब्रिड कापूस बियाणे', category: 'seeds', brand: 'Mahyco', dealerName: 'Shinde Krushi Seva Kendra', rating: 4.4, reviewsCount: 128, mrp: 1250, discountedPrice: 1090, bnplAvailable: true, batchNo: 'BATCH-2411A', quantity: 340, certifier: 'Agmark', certificateNo: 'AGM-2026-88112', certificateValid: true, imageUrl: '', status: 'active', userId: 'admin_root', createdAt: iso(21), updatedAt: iso(2) },
  { id: 'prod_1002', title: 'Urea 46% Nitrogen 45kg', vernacularTitle: 'युरिया ४६%', category: 'fertilizer', brand: 'IPL', dealerName: 'Jadhav Agro Agency', rating: 4.1, reviewsCount: 76, mrp: 290, discountedPrice: 266, bnplAvailable: false, batchNo: 'BATCH-2412C', quantity: 1200, certifier: 'Ministry of Agriculture', certificateNo: 'MOA-FCL-55021', certificateValid: true, imageUrl: '', status: 'active', userId: 'admin_root', createdAt: iso(18), updatedAt: iso(1) },
  { id: 'prod_1003', title: 'Imidacloprid 17.8% SL 500ml', vernacularTitle: 'इमिडाक्लोप्रिड 500ml', category: 'pesticide', brand: 'Bayer', dealerName: 'Patil Pesticides', rating: 3.9, reviewsCount: 41, mrp: 720, discountedPrice: 645, bnplAvailable: false, batchNo: 'BATCH-2410B', quantity: 85, certifier: 'CIB&RC', certificateNo: 'CIB-9-2026-4417', certificateValid: false, imageUrl: '', status: 'flagged', userId: 'admin_root', createdAt: iso(15), updatedAt: iso(3) },
  { id: 'prod_1004', title: 'Knapsack Manual Sprayer 16L', vernacularTitle: 'हाताने फवारणी यंत्र 16L', category: 'tools', brand: 'Aspee', dealerName: 'Shinde Krushi Seva Kendra', rating: 4.6, reviewsCount: 203, mrp: 2400, discountedPrice: 1999, bnplAvailable: true, batchNo: '', quantity: 56, certifier: '', certificateNo: '', certificateValid: false, imageUrl: '', status: 'active', userId: 'admin_root', createdAt: iso(11), updatedAt: iso(4) },
  { id: 'prod_1005', title: 'Mini Power Tiller 5HP', vernacularTitle: 'मिनी पॉवर टिलर', category: 'vehicles', brand: 'VST Shakti', dealerName: 'Deshmukh Farm Machinery', rating: 4.2, reviewsCount: 18, mrp: 165000, discountedPrice: 158500, bnplAvailable: true, batchNo: '', quantity: 4, certifier: 'BIS', certificateNo: 'BIS-2026-7731', certificateValid: true, imageUrl: '', status: 'discontinued', userId: 'admin_root', createdAt: iso(40), updatedAt: iso(6) },
]

export const demoOrders = [
  { id: 'ordoc_1', orderId: 'ord_5521', userId: 'usr_ram01', userName: 'Ram Patil', items: [{ productId: 'prod_1001', title: 'Hybrid Cotton Seeds BG-II', quantity: 2, unitPrice: 1090 }], total: 2180, paymentMethod: 'upi', paymentStatus: 'paid', razorpayOrderId: 'order_Mx8q2Lc', razorpayPaymentId: 'pay_N21vXa9', status: 'delivered', statusHistory: [{ status: 'placed', at: iso(9, 9) }, { status: 'confirmed', at: iso(9, 11) }, { status: 'packed', at: iso(8) }, { status: 'shipped', at: iso(7) }, { status: 'outForDelivery', at: iso(6) }, { status: 'delivered', at: iso(6, 16) }], refundStatus: 'notApplicable', deliveryAddress: 'House 12, Waghapur Road, Yavatmal, Maharashtra 445001', createdAt: iso(9, 9), updatedAt: iso(6, 16) },
  { id: 'ordoc_2', orderId: 'ord_5522', userId: 'usr_suresh7', userName: 'Suresh Jadhav', items: [{ productId: 'prod_1002', title: 'Urea 46% Nitrogen 45kg', quantity: 10, unitPrice: 266 }], total: 2660, paymentMethod: 'bnpl', paymentStatus: 'pending', razorpayOrderId: '', razorpayPaymentId: '', status: 'confirmed', statusHistory: [{ status: 'placed', at: iso(3, 8) }, { status: 'confirmed', at: iso(3, 12) }], refundStatus: 'notApplicable', deliveryAddress: 'Plot 4, MIDC Road, Washim, Maharashtra 444505', createdAt: iso(3, 8), updatedAt: iso(3, 12) },
  { id: 'ordoc_3', orderId: 'ord_5523', userId: 'usr_mahadev3', userName: 'Mahadev Shinde', items: [{ productId: 'prod_1003', title: 'Imidacloprid 17.8% SL 500ml', quantity: 3, unitPrice: 645 }, { productId: 'prod_1004', title: 'Knapsack Manual Sprayer 16L', quantity: 1, unitPrice: 1999 }], total: 3934, paymentMethod: 'upi', paymentStatus: 'refunded', razorpayOrderId: 'order_Mx9k1Pz', razorpayPaymentId: 'pay_N30dQr2', status: 'cancelled', statusHistory: [{ status: 'placed', at: iso(2, 10) }, { status: 'confirmed', at: iso(2, 13) }, { status: 'cancelled', at: iso(1, 9) }], refundStatus: 'refunded', razorpayRefundId: 'rfnd_N31aBc8', cancelReason: 'Found cheaper elsewhere', deliveryAddress: 'Ner Parsopant, Yavatmal, Maharashtra 445102', createdAt: iso(2, 10), updatedAt: iso(1, 9) },
  { id: 'ordoc_4', orderId: 'ord_5524', userId: 'usr_ganesh9', userName: 'Ganesh More', items: [{ productId: 'prod_1004', title: 'Knapsack Manual Sprayer 16L', quantity: 2, unitPrice: 1999 }], total: 3998, paymentMethod: 'cod', paymentStatus: 'pending', razorpayOrderId: '', razorpayPaymentId: '', status: 'placed', statusHistory: [{ status: 'placed', at: iso(0, 7) }], refundStatus: 'notApplicable', deliveryAddress: 'Karanja Ghadge, Washim, Maharashtra 444406', createdAt: iso(0, 7), updatedAt: iso(0, 7) },
  { id: 'ordoc_5', orderId: 'ord_5525', userId: 'usr_priya22', userName: 'Priya Kale', items: [{ productId: 'prod_1001', title: 'Hybrid Cotton Seeds BG-II', quantity: 5, unitPrice: 1090 }], total: 5450, paymentMethod: 'upi', paymentStatus: 'paid', razorpayOrderId: 'order_My1t8Rw', razorpayPaymentId: 'pay_N41sTe5', status: 'shipped', statusHistory: [{ status: 'placed', at: iso(4, 9) }, { status: 'confirmed', at: iso(4, 10) }, { status: 'packed', at: iso(3, 15) }, { status: 'shipped', at: iso(2, 11) }], refundStatus: 'notApplicable', deliveryAddress: 'Digras Taluka, Yavatmal, Maharashtra 445203', createdAt: iso(4, 9), updatedAt: iso(2, 11) },
]
