import {
  Wheat,
  Tractor,
  Leaf,
  Landmark,
  Sparkles,
  ShieldCheck,
  TrendingUp,
  Package,
  ShoppingCart,
  FileText,
  Truck,
  MapPin,
  Cpu,
  MessageSquare,
  BookOpen,
  Shield,
  Layers,
  Droplets,
  Network,
  HeartPulse,
  Video,
  Trees,
  Award,
  CloudSun,
  HandHeart,
  Coins,
  Sliders,
  Users,
  FileCheck,
  LayoutDashboard
} from 'lucide-react';

export const NAVIGATION_GROUPS = [
  {
    id: 'commerce',
    title: 'Agri-Commerce & Trade',
    shortTitle: 'Commerce',
    icon: Wheat,
    color: 'emerald',
    badge: '5 Modules',
    description: 'Mandi pricing, B2B trading, marketplace orders and FPO pools',
    modules: ['04', '05', '06', '07', '18'],
  },
  {
    id: 'operations',
    title: 'Farm Operations & Land',
    shortTitle: 'Operations',
    icon: Tractor,
    color: 'agro',
    badge: '6 Modules',
    description: 'Fleet transport, farm machinery, land disputes, 7/12 & water intelligence',
    modules: ['08', '09', '10', '16', '13', '17'],
  },
  {
    id: 'ecology',
    title: 'Ecology, Climate & Livestock',
    shortTitle: 'Ecology',
    icon: Leaf,
    color: 'teal',
    badge: '3 Modules',
    description: 'Livestock health, agroforestry carbon sinks and CA cold storage',
    modules: ['19', '21', '23'],
  },
  {
    id: 'finance',
    title: 'Agri-Finance & Insurance',
    shortTitle: 'Finance',
    icon: Landmark,
    color: 'amber',
    badge: '4 Modules',
    description: 'Kisan banking, PMFBY crop insurance, Women SHGs and automated settlements',
    modules: ['14', '15', '24', '25'],
  },
  {
    id: 'advisory',
    title: 'AI Advisory & Community',
    shortTitle: 'Advisory',
    icon: Sparkles,
    color: 'blue',
    badge: '4 Modules',
    description: 'Agronomy AI models, vernacular chatbot, video gyan and farmer rewards',
    modules: ['11', '12', '20', '22'],
  },
  {
    id: 'governance',
    title: 'Platform, Security & System',
    shortTitle: 'Governance',
    icon: ShieldCheck,
    color: 'purple',
    badge: '4 Modules',
    description: 'RBAC permissions, 6 user personas, KYC vault, remote config & moderation',
    modules: ['01', '02', '03', '26'],
  },
];

export const ALL_MODULES_MAP = {
  '01': {
    id: '01',
    groupId: 'governance',
    title: 'Authentication, RBAC & Security',
    shortTitle: 'Auth & RBAC',
    sop: 'SOP-01',
    path: '/admin/auth',
    icon: ShieldCheck,
    gradient: 'from-emerald-500 to-teal-700',
    collections: 'users, auth_tokens, devices, sessions',
    compliance: 'FastAPI Endpoints: 6 Implemented • Pytest 9.1.1: 13/13 Passed'
  },
  '02': {
    id: '02',
    groupId: 'governance',
    title: 'User Profiles & Multi-Persona Engine',
    shortTitle: 'User Management',
    sop: 'SOP-02',
    path: '/admin/users',
    icon: Users,
    gradient: 'from-teal-500 to-emerald-700',
    collections: 'users, users/{uid}/role_profiles, users/{uid}/bookings',
    compliance: '6 Personas Supported • Satellite Polygon Geofencing: Active'
  },
  '03': {
    id: '03',
    groupId: 'governance',
    title: 'KYC Verification & Document Vault',
    shortTitle: 'KYC & Vault',
    sop: 'SOP-03',
    path: '/admin/kyc',
    icon: FileCheck,
    gradient: 'from-emerald-600 to-teal-800',
    collections: 'kyc_submissions, audit_logs',
    compliance: 'DPDP Aadhaar Masking • OCR Verification Gateway'
  },
  '04': {
    id: '04',
    groupId: 'commerce',
    title: 'Mandi Prices, Vyapari Live Rates & Approvals',
    shortTitle: 'Mandi Rates',
    sop: 'SOP-04',
    path: '/admin/mandi',
    icon: TrendingUp,
    gradient: 'from-emerald-500 to-green-700',
    collections: 'mandi_rates, vyapari_daily_rates',
    compliance: 'APMC Market Intelligence • Redis Sub-5ms Caching'
  },
  '05': {
    id: '05',
    groupId: 'commerce',
    title: 'Produce Lots & B2B Trading',
    shortTitle: 'Produce Lots',
    sop: 'SOP-05',
    path: '/admin/lots',
    icon: Package,
    gradient: 'from-emerald-500 to-teal-700',
    collections: 'produce_lots, lot_bids',
    compliance: 'Assay Quality Grading • Escrow Payment Holds'
  },
  '06': {
    id: '06',
    groupId: 'commerce',
    title: 'Marketplace, Agri-Inputs & Orders',
    shortTitle: 'Marketplace & Orders',
    sop: 'SOP-06',
    path: '/admin/marketplace',
    icon: ShoppingCart,
    gradient: 'from-emerald-600 to-green-800',
    collections: 'products, orders, carts',
    compliance: 'Fertilizer Licensing Verified • Direct-to-Farm Logistics'
  },
  '07': {
    id: '07',
    groupId: 'commerce',
    title: 'Buyer Contracts & Escrow Agreement',
    shortTitle: 'Contracts & Escrow',
    sop: 'SOP-07',
    path: '/admin/contracts',
    icon: FileText,
    gradient: 'from-emerald-500 to-teal-700',
    collections: 'contracts, escrow_milestones',
    compliance: 'Farmer Protection Clause • Bank Guarantee Verification'
  },
  '08': {
    id: '08',
    groupId: 'operations',
    title: 'Transport Logistics & Fleet Dispatch',
    shortTitle: 'Transport & Fleet',
    sop: 'SOP-08',
    path: '/admin/transport',
    icon: Truck,
    gradient: 'from-emerald-500 to-green-700',
    collections: 'vehicles, bookings, settlements',
    compliance: 'Vahan Telemetry Verified • Geofenced Farm Pickups'
  },
  '09': {
    id: '09',
    groupId: 'operations',
    title: 'Farm Equipment, Machinery & Rental Hub',
    shortTitle: 'Equipment Rental',
    sop: 'SOP-09',
    path: '/admin/equipment',
    icon: Tractor,
    gradient: 'from-green-600 to-emerald-800',
    collections: 'equipment, equipment_rentals',
    compliance: 'Custom Hiring Center (CHC) Subsidies Supported'
  },
  '10': {
    id: '10',
    groupId: 'operations',
    title: 'Land Leasing, Demarcation & Dispute Resolution',
    shortTitle: 'Land Leasing & Disputes',
    sop: 'SOP-10',
    path: '/admin/land',
    icon: MapPin,
    gradient: 'from-emerald-500 to-teal-700',
    collections: 'land_parcels, land_leases, land_disputes',
    compliance: 'Survey Number Georeferenced • Satellite Verification'
  },
  '11': {
    id: '11',
    groupId: 'advisory',
    title: 'AI Crop Advisory & Disease Diagnosis Models',
    shortTitle: 'AI Advisory Models',
    sop: 'SOP-11',
    path: '/admin/ai-advisory',
    icon: Cpu,
    gradient: 'from-teal-500 to-emerald-700',
    collections: 'ai_advisories, diagnostic_scans',
    compliance: 'ICAR Agronomic Calibration • Sub-Second Inference'
  },
  '12': {
    id: '12',
    groupId: 'advisory',
    title: 'Vernacular Chatbot, Voice & Expert Handoff',
    shortTitle: 'Chatbot & Handoff',
    sop: 'SOP-12',
    path: '/admin/chatbot',
    icon: MessageSquare,
    gradient: 'from-emerald-500 to-teal-700',
    collections: 'bot_conversations, agent_handoffs',
    compliance: '12 Indian Regional Languages Supported • Audio Streaming'
  },
  '13': {
    id: '13',
    groupId: 'operations',
    title: 'Farm Diary, Crop Cycle & PnL Ledger',
    shortTitle: 'Farm Diary & PnL',
    sop: 'SOP-13',
    path: '/admin/diary',
    icon: BookOpen,
    gradient: 'from-green-600 to-teal-800',
    collections: 'farm_diaries, crop_activities',
    compliance: 'Cost of Cultivation Benchmarking • Double Entry Audit'
  },
  '14': {
    id: '14',
    groupId: 'finance',
    title: 'Banking, Kisan Credit & Microfinance Underwriting',
    shortTitle: 'Banking & Underwriting',
    sop: 'SOP-14',
    path: '/admin/finance',
    icon: Landmark,
    gradient: 'from-emerald-600 to-teal-800',
    collections: 'bank_accounts, loan_applications, kcc_records',
    compliance: 'Penny-Drop Verification: Active • Kisan Credit Score: Enforced • Dual Sign-off > ₹50,000: Enforced'
  },
  '15': {
    id: '15',
    groupId: 'finance',
    title: 'Crop Insurance (PMFBY) & Calamity Claims Desk',
    shortTitle: 'Insurance & Claims',
    sop: 'SOP-15',
    path: '/admin/insurance',
    icon: Shield,
    gradient: 'from-teal-500 to-emerald-700',
    collections: 'insurance_policies, insurance_claims, insurance_rates',
    compliance: 'PMFBY 72-Hour Calamity Intimation • Geotagged Damage Verification • Dual Sign-off > ₹50,000 • Aadhaar Masking'
  },
  '16': {
    id: '16',
    groupId: 'operations',
    title: 'Land Records Registry (7/12 & 8A Utara)',
    shortTitle: 'Land Registry (7/12)',
    sop: 'SOP-16',
    path: '/admin/land-records',
    icon: Layers,
    gradient: 'from-emerald-600 to-teal-700',
    collections: 'land_records_712, users/{uid}/imported_records',
    compliance: 'Mahabhulekh Gateway: Active • Redis L2 Cache: Sub-5ms • DPDP Aadhaar Masking: PASS • Audit Logging: Enforced'
  },
  '17': {
    id: '17',
    groupId: 'operations',
    title: 'Water Intelligence, Canal Rotation & Irrigation',
    shortTitle: 'Water & Irrigation',
    sop: 'SOP-17',
    path: '/admin/water',
    icon: Droplets,
    gradient: 'from-teal-500 to-emerald-700',
    collections: 'water_schedules, cgwb_stations, canal_schedules',
    compliance: 'CGWB Piezometer Telemetry: Active • Canal Rotation Dispatch: Enforced • PMKSY 55% Cap: Enforced • Dual Sign-off > ₹50,000'
  },
  '18': {
    id: '18',
    groupId: 'commerce',
    title: 'FPO Engine & Bulk Procurement Pools',
    shortTitle: 'FPO & Pool Mgmt',
    sop: 'SOP-18',
    path: '/admin/fpo',
    icon: Network,
    gradient: 'from-green-600 to-emerald-800',
    collections: 'fpos, fpo_pools, fpo_pool_members',
    compliance: 'ROC CIN & NABARD Empanelment: Verified • Escrow Dual Sign-off > ₹50,000 • DPDP Masking: Enforced'
  },
  '19': {
    id: '19',
    groupId: 'ecology',
    title: 'Livestock, Dairy & Veterinary Services',
    shortTitle: 'Livestock & Dairy',
    sop: 'SOP-19',
    path: '/admin/livestock',
    icon: HeartPulse,
    gradient: 'from-emerald-500 to-teal-700',
    collections: 'gaushalas, nurseries, vets, dairy_products, vet_bookings, manure_orders',
    compliance: 'MSVC Vet Licensure: Verified • 80G Gaushala Audit: Active • NABL A2 Purity: Enforced • Dual Sign-off > ₹50,000'
  },
  '20': {
    id: '20',
    groupId: 'advisory',
    title: 'Knowledge Hub, Content CMS & Live Media',
    shortTitle: 'Content CMS & Gyan',
    sop: 'SOP-20',
    path: '/admin/content',
    icon: Video,
    gradient: 'from-emerald-600 to-teal-700',
    collections: 'agri_news, agri_channels, workshops, expert_talks, video_guides, blog_articles',
    compliance: 'RTMP Stream Key Security: Verified • ICAR Certification: Enforced • Live Chat Moderation: Active • DPDP Masking: Enforced'
  },
  '21': {
    id: '21',
    groupId: 'ecology',
    title: 'Agroforestry, Tree Plantation & Biofuel',
    shortTitle: 'Agroforestry & Trees',
    sop: 'SOP-21',
    path: '/admin/tree',
    icon: Trees,
    gradient: 'from-green-600 to-emerald-800',
    collections: 'tree_articles, ngos, biofuel_trees, tree_care_guides, sapling_requests',
    compliance: 'Max 500 Saplings Cap: Enforced • NGO 80G/Darpan Audited: Verified • Geo-Survival Tracking: Active • Dual Sign-off > ₹50,000'
  },
  '22': {
    id: '22',
    groupId: 'advisory',
    title: 'Gamification, Krishi Ratna & Referrals',
    shortTitle: 'Gamification Economy',
    sop: 'SOP-22',
    path: '/admin/ratings',
    icon: Award,
    gradient: 'from-emerald-500 to-green-700',
    collections: 'gamification_status, agri_coins_ledger, reward_coupons, referrals, ratings',
    compliance: 'AgriCoins Circulation: Monitored • Referral Fraud Detection: Active • Dual Sign-off > ₹50,000 • DPDP Masking: Enforced'
  },
  '23': {
    id: '23',
    groupId: 'ecology',
    title: 'Climate Resilience, Carbon Credits & Cold Storage',
    shortTitle: 'Climate & Cold Storage',
    sop: 'SOP-23',
    path: '/admin/climate',
    icon: CloudSun,
    gradient: 'from-teal-500 to-emerald-700',
    collections: 'cold_storages, cold_storage_bookings, climate_varieties, carbon_audits, produce_gradings',
    compliance: 'CA Storage Telemetry: Active • Carbon Credit Registry: Audited • Dual Sign-off > ₹50,000 • DPDP Masking'
  },
  '24': {
    id: '24',
    groupId: 'finance',
    title: 'Women in Agriculture & Self Help Groups',
    shortTitle: 'Women SHG Programs',
    sop: 'SOP-24',
    path: '/admin/women',
    icon: HandHeart,
    gradient: 'from-emerald-600 to-green-800',
    collections: 'women_shgs, shg_deposits, home_enterprises, shg_subsidies',
    compliance: 'NRLM Cluster Linkage: Active • Duplicate Month Lock: Enforced • Dual Sign-off > ₹50,000 • DPDP Masking'
  },
  '25': {
    id: '25',
    groupId: 'finance',
    title: 'Financial Settlements & Scheduled Jobs',
    shortTitle: 'Financial Settlements',
    sop: 'SOP-25',
    path: '/admin/settlements',
    icon: Coins,
    gradient: 'from-green-600 to-emerald-700',
    collections: 'settlements, transporter_payouts, seller_payouts, cron_job_logs',
    compliance: 'T+1 Automated Reconciliation: Active • Dual Sign-off > ₹50,000 • GST Invoicing (18%) • DPDP Masking'
  },
  '26': {
    id: '26',
    groupId: 'governance',
    title: 'System Health, Remote Config, Broadcast & Moderation',
    shortTitle: 'System Config & Moderation',
    sop: 'SOP-26',
    path: '/admin/config',
    icon: Sliders,
    gradient: 'from-emerald-500 to-teal-700',
    collections: 'app_config, broadcasts, user_reports, user_blocks, user_consents, audit_logs',
    compliance: 'Microservices SLA: 99.98% • Remote Version Gating • Targeted FCM Push • Dual Sign-off Bans • DPDP Masking'
  },
  'overview': {
    id: 'overview',
    groupId: 'overview',
    title: 'Executive Command Center & National AgriTech Overview',
    shortTitle: 'Command Center',
    sop: 'HQ-EXEC-00',
    path: '/admin/overview',
    icon: LayoutDashboard,
    gradient: 'from-emerald-700 via-green-600 to-teal-700',
    collections: 'national_kpis, mandi_ticker, produce_escrow, canal_telemetry, audit_stream',
    compliance: 'FastAPI Telemetry: Active • 412 APMC Mandis Live • DPDP Masking Enforced • Dual Sign-off Ready'
  },
  '00': {
    id: 'overview',
    groupId: 'overview',
    title: 'Executive Command Center & National AgriTech Overview',
    shortTitle: 'Command Center',
    sop: 'HQ-EXEC-00',
    path: '/admin/overview',
    icon: LayoutDashboard,
    gradient: 'from-emerald-700 via-green-600 to-teal-700',
    collections: 'national_kpis, mandi_ticker, produce_escrow, canal_telemetry, audit_stream',
    compliance: 'FastAPI Telemetry: Active • 412 APMC Mandis Live • DPDP Masking Enforced • Dual Sign-off Ready'
  }
};

export const OVERVIEW_GROUP = {
  id: 'overview',
  title: 'Executive Command Center',
  shortTitle: 'Overview',
  icon: LayoutDashboard,
  color: 'emerald',
  badge: 'Live HQ',
  description: 'National agriculture telemetry, GMV metrics, mandi live feeds, and operational health',
  modules: ['overview']
};

export function getModuleById(id) {
  if (id === 'overview' || id === '00') return ALL_MODULES_MAP['overview'];
  return ALL_MODULES_MAP[id] || ALL_MODULES_MAP['overview'];
}

export function getGroupById(groupId) {
  if (groupId === 'overview') return OVERVIEW_GROUP;
  return NAVIGATION_GROUPS.find((g) => g.id === groupId) || OVERVIEW_GROUP;
}

