/**
 * AGROVERCITY SUPERADMIN — Module 21: Agroforestry, Tree Plantation & Biofuel
 * Document ID: SOP-21
 * Target Collections: sapling_requests, ngos, biofuel_trees, tree_care_guides, tree_articles
 */

export const mockSaplingRequests = [
  {
    id: 'sap_101',
    farmerId: 'usr_fm_8812',
    farmerName: 'Dnyanoba Tukaram More',
    farmerPhone: '+91 98XXX XX312',
    aadhaarMasked: 'XXXX-XXXX-4192',
    district: 'Ahmednagar',
    taluka: 'Sangamner',
    landAreaAcres: 3.5,
    surveyNumber712: '142/2A',
    speciesRequested: 'Melia Dubia (Malabar Neem)',
    treeCategory: 'timber',
    quantity: 350, // max 500 cap enforced
    allocatedNgoId: 'ngo_01',
    allocatedNgoName: 'Vanrai Afforestation Foundation',
    unitCostINR: 40,
    subsidyPct: 80,
    farmerPayableINR: 2800,
    status: 'approved',
    survivalRatePercent: 92,
    dispatchTrackingNo: 'TRK-MH-AGRO-8821',
    deliveryAddress: 'At Post Talegaon, Near Datta Temple, Sangamner',
    createdAt: '2026-09-18T10:15:00Z',
    updatedAt: '2026-09-20T14:20:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'sap_102',
    farmerId: 'usr_fm_8930',
    farmerName: 'Balasaheb Kisanrao Patil',
    farmerPhone: '+91 94XXX XX781',
    aadhaarMasked: 'XXXX-XXXX-8821',
    district: 'Solapur',
    taluka: 'Malshiras',
    landAreaAcres: 5.0,
    surveyNumber712: '89/1B',
    speciesRequested: 'Pongamia pinnata (Karanja)',
    treeCategory: 'biofuel',
    quantity: 500, // exact cap
    allocatedNgoId: 'ngo_02',
    allocatedNgoName: 'Sahyadri Bio-Energy Trust',
    unitCostINR: 35,
    subsidyPct: 100,
    farmerPayableINR: 0,
    status: 'dispatched',
    survivalRatePercent: 88,
    dispatchTrackingNo: 'TRK-MH-AGRO-8834',
    deliveryAddress: 'Gat No 89, Akluj Road, Malshiras',
    createdAt: '2026-09-16T11:40:00Z',
    updatedAt: '2026-09-19T09:30:00Z',
    userId: 'usr_admin_rahul'
  },
  {
    id: 'sap_103',
    farmerId: 'usr_fm_9120',
    farmerName: 'Suman Vishwanath Jadhav',
    farmerPhone: '+91 97XXX XX902',
    aadhaarMasked: 'XXXX-XXXX-2301',
    district: 'Kolhapur',
    taluka: 'Karveer',
    landAreaAcres: 2.0,
    surveyNumber712: '215/4',
    speciesRequested: 'Tissue Culture Bamboo (Balcooa)',
    treeCategory: 'bamboo',
    quantity: 200,
    allocatedNgoId: 'ngo_03',
    allocatedNgoName: 'Maharashtra Bamboo Development Board Partner',
    unitCostINR: 65,
    subsidyPct: 75,
    farmerPayableINR: 3250,
    status: 'pending',
    survivalRatePercent: null,
    dispatchTrackingNo: null,
    deliveryAddress: 'Shiroli Pulachi, Karveer, Kolhapur',
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-20T08:00:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'sap_104',
    farmerId: 'usr_fm_9441',
    farmerName: 'Vikas Shrirang Deshmukh',
    farmerPhone: '+91 99XXX XX445',
    aadhaarMasked: 'XXXX-XXXX-6612',
    district: 'Nashik',
    taluka: 'Dindori',
    landAreaAcres: 4.2,
    surveyNumber712: '67/3',
    speciesRequested: 'Burma Teak (Sagwan High-Girth)',
    treeCategory: 'timber',
    quantity: 400,
    allocatedNgoId: 'ngo_01',
    allocatedNgoName: 'Vanrai Afforestation Foundation',
    unitCostINR: 50,
    subsidyPct: 60,
    farmerPayableINR: 8000,
    status: 'delivered',
    survivalRatePercent: 95,
    dispatchTrackingNo: 'TRK-MH-AGRO-8790',
    deliveryAddress: 'Wani Khurd, Dindori',
    createdAt: '2026-09-10T14:30:00Z',
    updatedAt: '2026-09-17T16:00:00Z',
    userId: 'usr_admin_vikram'
  },
  {
    id: 'sap_105',
    farmerId: 'usr_fm_9580',
    farmerName: 'Maruti Baburao Ghodke',
    farmerPhone: '+91 98XXX XX009',
    aadhaarMasked: 'XXXX-XXXX-9912',
    district: 'Beed',
    taluka: 'Ashti',
    landAreaAcres: 1.5,
    surveyNumber712: '112/1',
    speciesRequested: 'Simarouba glauca (Paradise Tree)',
    treeCategory: 'biofuel',
    quantity: 150,
    allocatedNgoId: 'ngo_02',
    allocatedNgoName: 'Sahyadri Bio-Energy Trust',
    unitCostINR: 30,
    subsidyPct: 100,
    farmerPayableINR: 0,
    status: 'rejected',
    survivalRatePercent: null,
    dispatchTrackingNo: null,
    deliveryAddress: 'Murshadpur, Ashti',
    createdAt: '2026-09-12T09:10:00Z',
    updatedAt: '2026-09-14T11:20:00Z',
    userId: 'usr_admin_rahul'
  }
];

export const mockNgos = [
  {
    id: 'ngo_01',
    name: 'Vanrai Afforestation & Social Forestry Foundation',
    darpanId: 'MH/2021/0284910',
    trustRegNo: 'E-14920/Pune',
    has80G12A: true,
    contactPerson: 'Dr. Suhas Ramdas Shinde',
    contactPhone: '+91 98XXX XX210',
    district: 'Pune',
    headquarters: 'Pune, Maharashtra',
    nurseryAcres: 18.5,
    annualSaplingCapacity: 450000,
    currentStock: 182000,
    verified: true,
    status: 'verified',
    totalDistributed: 384000,
    createdAt: '2025-11-10T09:00:00Z',
    updatedAt: '2026-09-15T11:00:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'ngo_02',
    name: 'Sahyadri Bio-Energy & Rural Green Trust',
    darpanId: 'MH/2022/0319402',
    trustRegNo: 'F-22104/Satara',
    has80G12A: true,
    contactPerson: 'Anand Gopal Kulkarni',
    contactPhone: '+91 94XXX XX552',
    district: 'Satara',
    headquarters: 'Karad, Maharashtra',
    nurseryAcres: 12.0,
    annualSaplingCapacity: 300000,
    currentStock: 94000,
    verified: true,
    status: 'verified',
    totalDistributed: 215000,
    createdAt: '2026-01-14T10:00:00Z',
    updatedAt: '2026-09-18T14:30:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'ngo_03',
    name: 'Maharashtra Bamboo Development Board Partner',
    darpanId: 'MH/2023/0401928',
    trustRegNo: 'MBDB-EMP-2026-091',
    has80G12A: true,
    contactPerson: 'Arun V. Gawande',
    contactPhone: '+91 97XXX XX119',
    district: 'Chandrapur',
    headquarters: 'Chandrapur, Maharashtra',
    nurseryAcres: 25.0,
    annualSaplingCapacity: 600000,
    currentStock: 240000,
    verified: true,
    status: 'verified',
    totalDistributed: 512000,
    createdAt: '2026-02-20T12:00:00Z',
    updatedAt: '2026-09-19T10:00:00Z',
    userId: 'usr_admin_vikram'
  },
  {
    id: 'ngo_04',
    name: 'Vidarbha Vriksha Mitra Seva Sanstha',
    darpanId: 'MH/2025/0819441',
    trustRegNo: 'E-8821/Nagpur',
    has80G12A: false,
    contactPerson: 'Prakash B. Raut',
    contactPhone: '+91 91XXX XX401',
    district: 'Nagpur',
    headquarters: 'Nagpur, Maharashtra',
    nurseryAcres: 6.0,
    annualSaplingCapacity: 120000,
    currentStock: 35000,
    verified: false,
    status: 'pending_verification',
    totalDistributed: 42000,
    createdAt: '2026-07-10T14:00:00Z',
    updatedAt: '2026-09-20T16:00:00Z',
    userId: 'usr_admin_rahul'
  }
];

export const mockBiofuelTrees = [
  {
    id: 'bio_01',
    commonName: 'Karanja (Pongamia)',
    botanicalName: 'Pongamia pinnata',
    gestationYears: 4,
    oilContentPercent: 32,
    seedYieldKgPerTree: 45,
    annualGrossReturnPerAcreINR: 85000,
    co2SequestrationKgPerYear: 28,
    suitableSoil: 'Saline, Alkaline & Degraded Soils',
    buybackPartner: 'HPCL Biofuels & Indian Oil Bio-Refinery Solapur',
    marketRatePerKgINR: 28,
    status: 'active',
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-09-15T11:00:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'bio_02',
    commonName: 'Jatropha (Ratanjot)',
    botanicalName: 'Jatropha curcas',
    gestationYears: 3,
    oilContentPercent: 36,
    seedYieldKgPerTree: 3.5,
    annualGrossReturnPerAcreINR: 62000,
    co2SequestrationKgPerYear: 18,
    suitableSoil: 'Arid, Gravelly & Low Rainfall Belts',
    buybackPartner: 'BPCL Biodiesel Processing Center Nashik',
    marketRatePerKgINR: 32,
    status: 'active',
    createdAt: '2026-01-12T10:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'bio_03',
    commonName: 'Paradise Tree (Simarouba)',
    botanicalName: 'Simarouba glauca',
    gestationYears: 5,
    oilContentPercent: 60,
    seedYieldKgPerTree: 25,
    annualGrossReturnPerAcreINR: 98000,
    co2SequestrationKgPerYear: 32,
    suitableSoil: 'Red Laterite, Wasteland, Coastal Sands',
    buybackPartner: 'National Biofuel Development Board Pune',
    marketRatePerKgINR: 38,
    status: 'active',
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-09-18T10:00:00Z',
    userId: 'usr_admin_vikram'
  },
  {
    id: 'bio_04',
    commonName: 'Neem (Margosa)',
    botanicalName: 'Azadirachta indica',
    gestationYears: 5,
    oilContentPercent: 24,
    seedYieldKgPerTree: 50,
    annualGrossReturnPerAcreINR: 72000,
    co2SequestrationKgPerYear: 35,
    suitableSoil: 'Black Cotton, Sandy Clay & Drought-Prone',
    buybackPartner: 'RCF Trombay Neem Coating Facility',
    marketRatePerKgINR: 22,
    status: 'active',
    createdAt: '2026-02-15T12:00:00Z',
    updatedAt: '2026-09-19T09:00:00Z',
    userId: 'usr_admin_rahul'
  }
];

export const mockTreeCareGuides = [
  {
    id: 'guide_01',
    title: 'Melia Dubia (Malabar Neem) 0-24 Months Fast-Track Care',
    species: 'Melia Dubia',
    soilType: 'Deep well-drained red loamy or alluvial soil (pH 6.0 - 8.0)',
    pitDimensions: '1m x 1m x 1m dug 30 days prior with solarization',
    spacingMeters: '3m x 3m (440 trees/acre) or 4m x 4m (250 trees/acre)',
    irrigationSchedule: 'Weekly drip irrigation in summer (15 L/plant); bi-weekly in winter',
    pruningCycleMonths: 6,
    pestManagement: 'Termite protection using Chlorpyrifos/Imidacloprid drenching at transplanting; leaf spot spray with Mancozeb @ 2 g/L',
    survivalTips: 'Staking with bamboo poles during first 9 months prevents wind-tilt. Apply 10 kg FYM + 200g SSP per pit.',
    status: 'published',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'guide_02',
    title: 'High-Girth Teak (Sagwan) Tissue Culture Plantation Protocol',
    species: 'Tectona grandis',
    soilType: 'Deep fertile soils with minimum 1.5m root depth; avoid waterlogging',
    pitDimensions: '60cm x 60cm x 60cm filled with topsoil, neem cake & Vermicompost',
    spacingMeters: '2m x 2m for short rotation or 3m x 3m for timber saw-logs',
    irrigationSchedule: 'Fortnightly watering for initial 3 years. Cease irrigation in year 4 to induce heartwood formation.',
    pruningCycleMonths: 12,
    pestManagement: 'Defoliator (Hyblaea puera) control via Bacillus thuringiensis (Bt) spray @ 1.5 kg/ha; stem borer grease band application.',
    survivalTips: 'Debudding side shoots up to 5 meters height guarantees knot-free export-grade timber poles.',
    status: 'published',
    createdAt: '2026-03-15T11:00:00Z',
    updatedAt: '2026-09-12T16:00:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'guide_03',
    title: 'Bambusa balcooa Tissue Culture Clump Care & Biomass Harvesting',
    species: 'Bambusa balcooa',
    soilType: 'Tolerates moist clayey soils, riverbanks, and degraded canal sides',
    pitDimensions: '50cm x 50cm x 50cm with 5 kg compost and 100g Trichoderma',
    spacingMeters: '5m x 5m (160 clumps/acre) for automated cane harvesting',
    irrigationSchedule: 'Basal trench watering twice a month; flourishes with treated rural sewage or wastewater.',
    pruningCycleMonths: 12,
    pestManagement: 'Bamboo pit scale inspection; spray neem oil 10,000 ppm @ 3 ml/L.',
    survivalTips: 'Do not harvest canes in Year 1-3. Selectively harvest 3-year-old mature dark culms starting Year 4 onwards.',
    status: 'published',
    createdAt: '2026-04-02T09:00:00Z',
    updatedAt: '2026-09-16T15:00:00Z',
    userId: 'usr_admin_vikram'
  }
];

export const mockTreeArticles = [
  {
    id: 'art_01',
    title: 'Intercropping Turmeric & Ginger Under Melia Dubia Canopy: ₹2.4 Lakh/Acre Annual Cashflow',
    intercroppingModel: 'Melia Dubia (3m x 3m) + Salem Turmeric on Raised Beds',
    expectedPaybackYears: 2,
    carbonCreditEligible: true,
    contentSummary: 'Partial 35% shade from 2-year Melia Dubia foliage reduces sunburn in ginger/turmeric rhizomes while doubling land use efficiency index to 1.82.',
    readTimeMinutes: 6,
    author: 'Dr. Sharadrao Patil (Forestry Specialist)',
    status: 'published',
    createdAt: '2026-05-10T10:00:00Z',
    updatedAt: '2026-09-14T11:00:00Z',
    userId: 'usr_admin_ananya'
  },
  {
    id: 'art_02',
    title: 'Biofuel Bund Planting: Turning Non-Arable Field Boundaries into Diesel Revenue',
    intercroppingModel: 'Pongamia pinnata on 200m field borders (100 trees/km)',
    expectedPaybackYears: 4,
    carbonCreditEligible: true,
    contentSummary: 'Fencing field perimeters with drought-hardy Pongamia provides natural windbreaks, reduces evapotranspiration by 14%, and yields 4,000 kg seeds annually.',
    readTimeMinutes: 8,
    author: 'K. R. Deshpande (Soil & Bioenergy Cell)',
    status: 'published',
    createdAt: '2026-06-18T12:00:00Z',
    updatedAt: '2026-09-18T16:00:00Z',
    userId: 'usr_admin_rahul'
  }
];

export const mockAgroforestryAuditLogs = [
  {
    id: 'aud_tree_01',
    adminUid: 'usr_admin_ananya',
    adminName: 'Ananya Deshmukh (Super Admin)',
    timestamp: '2026-09-20T14:20:00Z',
    ipAddress: '10.0.4.15',
    actionType: 'APPROVE_SAPLING_REQUEST',
    entityId: 'sap_101',
    entityName: '350 Melia Dubia saplings for Dnyanoba More',
    collection: 'sapling_requests',
    previousState: 'pending',
    newState: 'approved',
    reason: 'Verified 7/12 land record (Survey 142/2A) and assigned Vanrai Nursery for dispatch. Enforced 500-sapling cap.'
  },
  {
    id: 'aud_tree_02',
    adminUid: 'usr_admin_rahul',
    adminName: 'Rahul Shinde (Support Operator)',
    timestamp: '2026-09-19T09:30:00Z',
    ipAddress: '10.0.4.22',
    actionType: 'DISPATCH_SAPLING_ORDER',
    entityId: 'sap_102',
    entityName: '500 Pongamia saplings for Balasaheb Patil',
    collection: 'sapling_requests',
    previousState: 'approved',
    newState: 'dispatched',
    reason: 'Generated gate pass and dispatch tracking TRK-MH-AGRO-8834 with 100% bio-energy subsidy clearance.'
  },
  {
    id: 'aud_tree_03',
    adminUid: 'usr_admin_ananya',
    adminName: 'Ananya Deshmukh (Super Admin)',
    timestamp: '2026-09-15T11:00:00Z',
    ipAddress: '10.0.4.15',
    actionType: 'VERIFY_AFFORESTATION_NGO',
    entityId: 'ngo_01',
    entityName: 'Vanrai Afforestation Foundation',
    collection: 'ngos',
    previousState: 'pending_verification',
    newState: 'verified',
    reason: 'Niti Aayog Darpan ID MH/2021/0284910 and 80G/12A certificates audited and renewed.'
  },
  {
    id: 'aud_tree_04',
    adminUid: 'usr_admin_rahul',
    adminName: 'Rahul Shinde (Support Operator)',
    timestamp: '2026-09-14T11:20:00Z',
    ipAddress: '10.0.4.22',
    actionType: 'REJECT_SAPLING_REQUEST',
    entityId: 'sap_105',
    entityName: 'Maruti Baburao Ghodke',
    collection: 'sapling_requests',
    previousState: 'pending',
    newState: 'rejected',
    reason: 'Land survey number mismatch against Mahabhulekh database; farmer requested to resubmit 7/12 extract.'
  }
];

export const mockAgroforestrySummary = {
  totalSaplingRequests: 1420,
  pendingReviewRequests: 18,
  approvedAndDispatched: 1340,
  totalSaplingsDistributed: 428000,
  activeNgosPartnered: 14,
  biofuelVarietiesTracked: 4,
  averageSurvivalRatePercent: 89.4,
  totalCarbonOffsetMT: 12400
};
