/**
 * AGROVERCITY SUPERADMIN — Module 24: Women in Agriculture & Self Help Groups
 * Document ID: SOP-24
 * Target Collections: women_shgs, shg_deposits, home_enterprises, shg_subsidies
 */

export const mockWomenShgs = [
  {
    id: 'shg_01',
    shgName: 'Savitribai Phule Mahila Bachat Gat',
    village: 'Ralegan Siddhi',
    block: 'Parner',
    district: 'Ahmednagar',
    state: 'Maharashtra',
    federationCluster: 'Parner Mahila Prabhav Samiti (NRLM Cluster-4)',
    presidentName: 'Sunita Shantaram Ghadge',
    presidentPhone: '+91 96XXX XX148',
    secretaryName: 'Mangala Devidas Pawar',
    secretaryPhone: '+91 98XXX XX321',
    membersCount: 16,
    bankName: 'Bank of Maharashtra',
    accountNumberMasked: '••••••••4921',
    ifscCode: 'MAHB0000412',
    savingsCorpusInr: 420000,
    internalLoanOutstandInr: 185000,
    recoveryRatePct: 99.4,
    weeklyMeetingDisciplinePct: 98,
    subventionEligibility: 'eligible',
    status: 'verified',
    verificationDocuments: [
      'NRLM Registration Certificate (MH/AHM/2021/8812)',
      'Bank of Maharashtra Account Passbook',
      'Gram Panchayat Resolution & Member Roster'
    ],
    verifiedBy: 'admin_rural_inclusion',
    formedYear: 2021,
    createdAt: '2025-04-10T10:00:00Z',
    updatedAt: '2026-09-18T14:20:00Z'
  },
  {
    id: 'shg_02',
    shgName: 'Jijamata Mahila Krishi Vikas Bachat Gat',
    village: 'Ozar',
    block: 'Niphad',
    district: 'Nashik',
    state: 'Maharashtra',
    federationCluster: 'Niphad Godavari Mahila Mahasangh',
    presidentName: 'Shashikala Balasaheb Shinde',
    presidentPhone: '+91 97XXX XX902',
    secretaryName: 'Alka Ramdas Gangurde',
    secretaryPhone: '+91 94XXX XX514',
    membersCount: 14,
    bankName: 'State Bank of India',
    accountNumberMasked: '••••••••8104',
    ifscCode: 'SBIN0002190',
    savingsCorpusInr: 580000,
    internalLoanOutstandInr: 290000,
    recoveryRatePct: 98.8,
    weeklyMeetingDisciplinePct: 95,
    subventionEligibility: 'disbursed',
    status: 'verified',
    verificationDocuments: [
      'MSRLM Umed Registration (MH/NSK/2019/3321)',
      'SBI Joint Account Authority Letter',
      'Micro-enterprise FSSAI Group Permit'
    ],
    verifiedBy: 'admin_rural_inclusion',
    formedYear: 2019,
    createdAt: '2025-05-18T09:30:00Z',
    updatedAt: '2026-09-19T11:15:00Z'
  },
  {
    id: 'shg_03',
    shgName: 'Ahilyabai Holkar Kisan Mahila Sangh',
    village: 'Karkamb',
    block: 'Pandharpur',
    district: 'Solapur',
    state: 'Maharashtra',
    federationCluster: 'Pandharpur Chandrabhaga Federation',
    presidentName: 'Surekha Dnyaneshwar Bagal',
    presidentPhone: '+91 91XXX XX439',
    secretaryName: 'Vimal Vithoba Salunkhe',
    secretaryPhone: '+91 93XXX XX882',
    membersCount: 12,
    bankName: 'Solapur District Central Co-op Bank',
    accountNumberMasked: '••••••••1290',
    ifscCode: 'HDFC0CSDCCB',
    savingsCorpusInr: 290000,
    internalLoanOutstandInr: 140000,
    recoveryRatePct: 96.5,
    weeklyMeetingDisciplinePct: 91,
    subventionEligibility: 'eligible',
    status: 'verified',
    verificationDocuments: [
      'DCCB Joint Passbook',
      'Cluster Linkage Agreement',
      'SHG Registration Letter'
    ],
    verifiedBy: 'admin_rural_inclusion',
    formedYear: 2022,
    createdAt: '2025-07-22T11:45:00Z',
    updatedAt: '2026-09-17T16:00:00Z'
  },
  {
    id: 'shg_04',
    shgName: 'Kranti Jyoti Savitri Kisan Bachat Gat',
    village: 'Bhusawal Rural',
    block: 'Bhusawal',
    district: 'Jalgaon',
    state: 'Maharashtra',
    federationCluster: 'Tapi River Women Agri Federation',
    presidentName: 'Usha Narayan Patil',
    presidentPhone: '+91 95XXX XX711',
    secretaryName: 'Lata Prabhakar Chaudhari',
    secretaryPhone: '+91 99XXX XX305',
    membersCount: 18,
    bankName: 'Central Bank of India',
    accountNumberMasked: '••••••••6723',
    ifscCode: 'CBIN0281092',
    savingsCorpusInr: 340000,
    internalLoanOutstandInr: 160000,
    recoveryRatePct: 97.2,
    weeklyMeetingDisciplinePct: 88,
    subventionEligibility: 'pending_approval',
    status: 'pending_verification',
    verificationDocuments: [
      'Application for NRLM Mission Shakti',
      'Central Bank Kyc Token Form'
    ],
    verifiedBy: null,
    formedYear: 2023,
    createdAt: '2026-08-10T14:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z'
  },
  {
    id: 'shg_05',
    shgName: 'Bhagyalakshmi Mahila Sheti Bachat Gat',
    village: 'Walwa',
    block: 'Islampur',
    district: 'Sangli',
    state: 'Maharashtra',
    federationCluster: 'Krishna Khore Mahila Vikas Manch',
    presidentName: 'Vandana Anandrao Patil',
    presidentPhone: '+91 92XXX XX540',
    secretaryName: 'Rekha Shamrao Mane',
    secretaryPhone: '+91 96XXX XX899',
    membersCount: 15,
    bankName: 'Sangli Urban Co-operative Bank',
    accountNumberMasked: '••••••••3409',
    ifscCode: 'SBLS0000012',
    savingsCorpusInr: 610000,
    internalLoanOutstandInr: 310000,
    recoveryRatePct: 99.8,
    weeklyMeetingDisciplinePct: 99,
    subventionEligibility: 'eligible',
    status: 'verified',
    verificationDocuments: [
      'MSRLM Cluster A Grade Certification',
      'Audited Financial Ledger 2025-26',
      'Bank Authorization Mandate'
    ],
    verifiedBy: 'admin_rural_inclusion',
    formedYear: 2020,
    createdAt: '2025-06-12T13:10:00Z',
    updatedAt: '2026-09-18T09:40:00Z'
  },
  {
    id: 'shg_06',
    shgName: 'Durga Mata Mahila Bachat Gat',
    village: 'Baramati Rural',
    block: 'Baramati',
    district: 'Pune',
    state: 'Maharashtra',
    federationCluster: 'Nira Valley Women Self Reliance CLF',
    presidentName: 'Kamal Sopanrao Jagtap',
    presidentPhone: '+91 98XXX XX667',
    secretaryName: 'Chhaya Ashok Jagtap',
    secretaryPhone: '+91 93XXX XX128',
    membersCount: 10,
    bankName: 'Bank of Baroda',
    accountNumberMasked: '••••••••9012',
    ifscCode: 'BARB0DBARAM',
    savingsCorpusInr: 175000,
    internalLoanOutstandInr: 95000,
    recoveryRatePct: 82.0,
    weeklyMeetingDisciplinePct: 74,
    subventionEligibility: 'ineligible',
    status: 'flagged_audit',
    verificationDocuments: [
      'Unreconciled Monthly Passbook Excerpt',
      'Meeting Attendance Irregularity Report'
    ],
    verifiedBy: 'admin_auditor',
    formedYear: 2024,
    createdAt: '2026-02-14T10:00:00Z',
    updatedAt: '2026-09-19T15:20:00Z'
  },
  {
    id: 'shg_07',
    shgName: 'Yashaswini Mahila Udhyog Bachat Gat',
    village: 'Paithan',
    block: 'Paithan',
    district: 'Chhatrapati Sambhajinagar',
    state: 'Maharashtra',
    federationCluster: 'Godavari Mahila Handloom & Agri Cluster',
    presidentName: 'Kaveri Pandurang Kale',
    presidentPhone: '+91 90XXX XX912',
    secretaryName: 'Sarita Bhagwan Shinde',
    secretaryPhone: '+91 97XXX XX243',
    membersCount: 20,
    bankName: 'Maharashtra Gramin Bank',
    accountNumberMasked: '••••••••7731',
    ifscCode: 'MAHG0004521',
    savingsCorpusInr: 520000,
    internalLoanOutstandInr: 260000,
    recoveryRatePct: 98.5,
    weeklyMeetingDisciplinePct: 94,
    subventionEligibility: 'eligible',
    status: 'verified',
    verificationDocuments: [
      'Handloom Weaver Registration',
      'Gramin Bank Account Clearance Certificate'
    ],
    verifiedBy: 'admin_rural_inclusion',
    formedYear: 2021,
    createdAt: '2025-08-05T09:00:00Z',
    updatedAt: '2026-09-20T12:30:00Z'
  },
  {
    id: 'shg_08',
    shgName: 'Pragati Mahila Bachat Gat',
    village: 'Umred',
    block: 'Umred',
    district: 'Nagpur',
    state: 'Maharashtra',
    federationCluster: 'Vidarbha Mahila Krishi Federation',
    presidentName: 'Asha Madhavrao Raut',
    presidentPhone: '+91 94XXX XX670',
    secretaryName: 'Meena Dilip Meshram',
    secretaryPhone: '+91 91XXX XX234',
    membersCount: 13,
    bankName: 'Punjab National Bank',
    accountNumberMasked: '••••••••5508',
    ifscCode: 'PUNB0182300',
    savingsCorpusInr: 210000,
    internalLoanOutstandInr: 110000,
    recoveryRatePct: 95.0,
    weeklyMeetingDisciplinePct: 89,
    subventionEligibility: 'pending_approval',
    status: 'pending_verification',
    verificationDocuments: [
      'Registration Form MSRLM / NRLM',
      'Member Resolution Minutes'
    ],
    verifiedBy: null,
    formedYear: 2024,
    createdAt: '2026-07-28T11:00:00Z',
    updatedAt: '2026-09-15T14:10:00Z'
  }
]

export const mockShgDeposits = [
  {
    id: 'shg_dep_101',
    shgId: 'shg_01',
    shgName: 'Savitribai Phule Mahila Bachat Gat',
    memberId: 'mem_201',
    memberName: 'Rukmini Vitthal Shinde',
    memberPhone: '+91 98XXX XX771',
    depositMonth: '2026-09',
    amountInr: 500,
    penaltyLateInr: 0,
    internalLoanRepaymentInr: 1200,
    internalInterestPaidInr: 120,
    paymentMode: 'UPI - Digital QR',
    depositDate: '2026-09-12',
    status: 'cleared',
    recordedBy: 'Mangala Devidas Pawar (Secretary)',
    createdAt: '2026-09-12T16:00:00Z',
    updatedAt: '2026-09-12T16:05:00Z'
  },
  {
    id: 'shg_dep_102',
    shgId: 'shg_01',
    shgName: 'Savitribai Phule Mahila Bachat Gat',
    memberId: 'mem_202',
    memberName: 'Sarubai Kisan Ghadge',
    memberPhone: '+91 96XXX XX381',
    depositMonth: '2026-09',
    amountInr: 500,
    penaltyLateInr: 0,
    internalLoanRepaymentInr: 800,
    internalInterestPaidInr: 80,
    paymentMode: 'Cash in SHG Box',
    depositDate: '2026-09-12',
    status: 'cleared',
    recordedBy: 'Mangala Devidas Pawar (Secretary)',
    createdAt: '2026-09-12T16:10:00Z',
    updatedAt: '2026-09-12T16:15:00Z'
  },
  {
    id: 'shg_dep_103',
    shgId: 'shg_02',
    shgName: 'Jijamata Mahila Krishi Vikas Bachat Gat',
    memberId: 'mem_215',
    memberName: 'Tarabai Narayan Gangurde',
    memberPhone: '+91 94XXX XX829',
    depositMonth: '2026-09',
    amountInr: 1000,
    penaltyLateInr: 0,
    internalLoanRepaymentInr: 2500,
    internalInterestPaidInr: 250,
    paymentMode: 'Bank NEFT',
    depositDate: '2026-09-10',
    status: 'cleared',
    recordedBy: 'Alka Ramdas Gangurde (Secretary)',
    createdAt: '2026-09-10T11:20:00Z',
    updatedAt: '2026-09-10T11:25:00Z'
  },
  {
    id: 'shg_dep_104',
    shgId: 'shg_02',
    shgName: 'Jijamata Mahila Krishi Vikas Bachat Gat',
    memberId: 'mem_216',
    memberName: 'Sushila Eknath Shinde',
    memberPhone: '+91 97XXX XX441',
    depositMonth: '2026-09',
    amountInr: 1000,
    penaltyLateInr: 50,
    internalLoanRepaymentInr: 1500,
    internalInterestPaidInr: 150,
    paymentMode: 'UPI - Digital QR',
    depositDate: '2026-09-15',
    status: 'cleared',
    recordedBy: 'Alka Ramdas Gangurde (Secretary)',
    createdAt: '2026-09-15T14:30:00Z',
    updatedAt: '2026-09-15T14:35:00Z'
  },
  {
    id: 'shg_dep_105',
    shgId: 'shg_03',
    shgName: 'Ahilyabai Holkar Kisan Mahila Sangh',
    memberId: 'mem_230',
    memberName: 'Indubai Dattatraya Salunkhe',
    memberPhone: '+91 91XXX XX890',
    depositMonth: '2026-09',
    amountInr: 500,
    penaltyLateInr: 0,
    internalLoanRepaymentInr: 1000,
    internalInterestPaidInr: 100,
    paymentMode: 'Cash in SHG Box',
    depositDate: '2026-09-14',
    status: 'cleared',
    recordedBy: 'Vimal Vithoba Salunkhe (Secretary)',
    createdAt: '2026-09-14T17:00:00Z',
    updatedAt: '2026-09-14T17:05:00Z'
  },
  {
    id: 'shg_dep_106',
    shgId: 'shg_05',
    shgName: 'Bhagyalakshmi Mahila Sheti Bachat Gat',
    memberId: 'mem_245',
    memberName: 'Laxmibai Shamrao Mane',
    memberPhone: '+91 92XXX XX119',
    depositMonth: '2026-09',
    amountInr: 1000,
    penaltyLateInr: 0,
    internalLoanRepaymentInr: 3000,
    internalInterestPaidInr: 300,
    paymentMode: 'UPI - Digital QR',
    depositDate: '2026-09-08',
    status: 'cleared',
    recordedBy: 'Rekha Shamrao Mane (Secretary)',
    createdAt: '2026-09-08T10:15:00Z',
    updatedAt: '2026-09-08T10:20:00Z'
  },
  {
    id: 'shg_dep_107',
    shgId: 'shg_06',
    shgName: 'Durga Mata Mahila Bachat Gat',
    memberId: 'mem_260',
    memberName: 'Parvati Baburao Jagtap',
    memberPhone: '+91 98XXX XX330',
    depositMonth: '2026-09',
    amountInr: 500,
    penaltyLateInr: 100,
    internalLoanRepaymentInr: 0,
    internalInterestPaidInr: 0,
    paymentMode: 'Cash in SHG Box',
    depositDate: '2026-09-18',
    status: 'flagged_discrepancy',
    recordedBy: 'Chhaya Ashok Jagtap (Secretary)',
    createdAt: '2026-09-18T18:00:00Z',
    updatedAt: '2026-09-19T09:30:00Z'
  },
  {
    id: 'shg_dep_108',
    shgId: 'shg_07',
    shgName: 'Yashaswini Mahila Udhyog Bachat Gat',
    memberId: 'mem_275',
    memberName: 'Chhayabai Bhagwan Shinde',
    memberPhone: '+91 90XXX XX821',
    depositMonth: '2026-09',
    amountInr: 800,
    penaltyLateInr: 0,
    internalLoanRepaymentInr: 1600,
    internalInterestPaidInr: 160,
    paymentMode: 'UPI - Digital QR',
    depositDate: '2026-09-11',
    status: 'cleared',
    recordedBy: 'Sarita Bhagwan Shinde (Secretary)',
    createdAt: '2026-09-11T12:45:00Z',
    updatedAt: '2026-09-11T12:50:00Z'
  }
]

export const mockHomeEnterprises = [
  {
    id: 'ent_prd_01',
    shgId: 'shg_01',
    shgName: 'Savitribai Phule Mahila Bachat Gat',
    artisanName: 'Sunita Shantaram Ghadge',
    artisanPhone: '+91 96XXX XX148',
    productTitle: 'Traditional Mango Pickle (Mustard Oil & Methi Sambhar)',
    category: 'Pickles & Chutneys',
    netWeight: '1 kg Jar',
    priceInr: 320,
    costToProduceInr: 190,
    stockUnits: 180,
    fssaiRegistration: 'FSSAI-21524198000412',
    organicCert: 'Jaivik Bharat PGS-India',
    qcRating: 4.9,
    totalSoldUnits: 640,
    revenueGeneratedInr: 204800,
    status: 'approved',
    curationNotes: 'Airtight food-grade glass jar; tested for microbiological safety at NABL lab',
    createdAt: '2025-08-10T10:00:00Z',
    updatedAt: '2026-09-19T14:00:00Z'
  },
  {
    id: 'ent_prd_02',
    shgId: 'shg_01',
    shgName: 'Savitribai Phule Mahila Bachat Gat',
    artisanName: 'Mangala Devidas Pawar',
    artisanPhone: '+91 98XXX XX321',
    productTitle: 'Sun-Dried Crunchy Urad Dal Papad (Black Pepper Infused)',
    category: 'Papad & Snacks',
    netWeight: '500 g Pack',
    priceInr: 180,
    costToProduceInr: 95,
    stockUnits: 250,
    fssaiRegistration: 'FSSAI-21524198000412',
    organicCert: 'Local Natural Farm Produce',
    qcRating: 4.8,
    totalSoldUnits: 820,
    revenueGeneratedInr: 147600,
    status: 'approved',
    curationNotes: 'Crisp roll texture; salt calibrated strictly within dietary guidelines',
    createdAt: '2025-09-02T11:15:00Z',
    updatedAt: '2026-09-18T16:30:00Z'
  },
  {
    id: 'ent_prd_03',
    shgId: 'shg_02',
    shgName: 'Jijamata Mahila Krishi Vikas Bachat Gat',
    artisanName: 'Shashikala Balasaheb Shinde',
    artisanPhone: '+91 97XXX XX902',
    productTitle: 'Kolhapuri Kanda-Lasun (Onion-Garlic) Masala Ground Blend',
    category: 'Spices & Masalas',
    netWeight: '250 g Pouch',
    priceInr: 160,
    costToProduceInr: 85,
    stockUnits: 320,
    fssaiRegistration: 'FSSAI-21523089000109',
    organicCert: 'NPOP Organic Verified',
    qcRating: 4.9,
    totalSoldUnits: 1100,
    revenueGeneratedInr: 176000,
    status: 'approved',
    curationNotes: 'Stone-pounded authentic red aroma; nitrogen-flushed foil pouch',
    createdAt: '2025-10-14T09:00:00Z',
    updatedAt: '2026-09-20T11:20:00Z'
  },
  {
    id: 'ent_prd_04',
    shgId: 'shg_03',
    shgName: 'Ahilyabai Holkar Kisan Mahila Sangh',
    artisanName: 'Surekha Dnyaneshwar Bagal',
    artisanPhone: '+91 91XXX XX439',
    productTitle: 'Cold-Pressed Wood-Churned (Lakdi Ghana) Groundnut Oil',
    category: 'Cold-Pressed Oils',
    netWeight: '1 Litre Can',
    priceInr: 340,
    costToProduceInr: 220,
    stockUnits: 95,
    fssaiRegistration: 'FSSAI-21524056000918',
    organicCert: 'Jaivik Bharat / AGMARK-A',
    qcRating: 4.9,
    totalSoldUnits: 450,
    revenueGeneratedInr: 153000,
    status: 'approved',
    curationNotes: 'Unrefined, unbleached, rich natural peanut aroma and antioxidants',
    createdAt: '2025-11-20T14:30:00Z',
    updatedAt: '2026-09-17T10:15:00Z'
  },
  {
    id: 'ent_prd_05',
    shgId: 'shg_05',
    shgName: 'Bhagyalakshmi Mahila Sheti Bachat Gat',
    artisanName: 'Vandana Anandrao Patil',
    artisanPhone: '+91 92XXX XX540',
    productTitle: 'Organic Jowar & Bajra Multi-Millet Sprouted Flour',
    category: 'Organic Millets & Flours',
    netWeight: '1 kg Kraft Bag',
    priceInr: 140,
    costToProduceInr: 75,
    stockUnits: 200,
    fssaiRegistration: 'FSSAI-21523098000774',
    organicCert: 'PGS-India Green Certificate',
    qcRating: 4.7,
    totalSoldUnits: 580,
    revenueGeneratedInr: 81200,
    status: 'approved',
    curationNotes: 'Low glycemic index diabetic friendly; solar dried sprouted grain',
    createdAt: '2026-01-18T10:20:00Z',
    updatedAt: '2026-09-19T09:00:00Z'
  },
  {
    id: 'ent_prd_06',
    shgId: 'shg_07',
    shgName: 'Yashaswini Mahila Udhyog Bachat Gat',
    artisanName: 'Kaveri Pandurang Kale',
    artisanPhone: '+91 90XXX XX912',
    productTitle: 'Handcrafted Paithani Silk Border Dupatta (Natural Dyes)',
    category: 'Handlooms & Handicrafts',
    netWeight: '1 Piece',
    priceInr: 1850,
    costToProduceInr: 950,
    stockUnits: 40,
    fssaiRegistration: 'N/A (Weavers Guild Reg)',
    organicCert: 'India Handloom Brand (IHB)',
    qcRating: 5.0,
    totalSoldUnits: 65,
    revenueGeneratedInr: 120250,
    status: 'approved',
    curationNotes: 'Pure zari weave with authentic peacock pallu; GI tag Paithan origin',
    createdAt: '2026-03-10T12:00:00Z',
    updatedAt: '2026-09-18T15:45:00Z'
  },
  {
    id: 'ent_prd_07',
    shgId: 'shg_04',
    shgName: 'Kranti Jyoti Savitri Kisan Bachat Gat',
    artisanName: 'Usha Narayan Patil',
    artisanPhone: '+91 95XXX XX711',
    productTitle: 'Dehydrated Raw Banana Crisps (Rock Salt & Cumin)',
    category: 'Papad & Snacks',
    netWeight: '200 g Pack',
    priceInr: 85,
    costToProduceInr: 42,
    stockUnits: 150,
    fssaiRegistration: 'FSSAI-App-Pending-9182',
    organicCert: 'Self-Certified Clean Farming',
    qcRating: 4.4,
    totalSoldUnits: 120,
    revenueGeneratedInr: 10200,
    status: 'pending_review',
    curationNotes: 'Submitted for batch shelf-life testing and final FSSAI license clearance',
    createdAt: '2026-09-05T15:30:00Z',
    updatedAt: '2026-09-16T11:00:00Z'
  },
  {
    id: 'ent_prd_08',
    shgId: 'shg_06',
    shgName: 'Durga Mata Mahila Bachat Gat',
    artisanName: 'Kamal Sopanrao Jagtap',
    artisanPhone: '+91 98XXX XX667',
    productTitle: 'Home-style Amla Murabba (Wild Forest Honey Syrup)',
    category: 'Pickles & Chutneys',
    netWeight: '500 g Jar',
    priceInr: 210,
    costToProduceInr: 110,
    stockUnits: 60,
    fssaiRegistration: 'FSSAI-Expired-Review-Required',
    organicCert: 'None',
    qcRating: 3.8,
    totalSoldUnits: 90,
    revenueGeneratedInr: 18900,
    status: 'changes_requested',
    curationNotes: 'Label lacks mandatory nutritional panel and batch expiry date; FSSAI renewal needed',
    createdAt: '2026-08-15T11:00:00Z',
    updatedAt: '2026-09-19T14:10:00Z'
  }
]

export const mockShgSubsidies = [
  {
    id: 'sub_01',
    shgId: 'shg_01',
    shgName: 'Savitribai Phule Mahila Bachat Gat',
    schemeName: 'NRLM Mission Shakti Interest Subvention (7% to 3% Cap)',
    grantType: 'Interest Subvention',
    amountInr: 64500, // > ₹50,000 -> Dual sign-off required!
    bankReferenceUtr: 'MAHB260918491823',
    status: 'disbursed',
    disbursedDate: '2026-09-18',
    dualSignOffRequired: true,
    signOffAdmin1: 'superadmin@agrovercity.org',
    signOffAdmin2: 'director.women@agrovercity.in',
    justification: 'Achieved 99.4% prompt repayment on internal & bank loans over consecutive 12 months',
    createdAt: '2026-09-10T10:00:00Z',
    updatedAt: '2026-09-18T15:20:00Z'
  },
  {
    id: 'sub_02',
    shgId: 'shg_02',
    shgName: 'Jijamata Mahila Krishi Vikas Bachat Gat',
    schemeName: 'Community Investment Fund (CIF) Agro-Processing Seed Capital',
    grantType: 'Community Investment Fund (CIF)',
    amountInr: 85000, // > ₹50,000 -> Dual sign-off required!
    bankReferenceUtr: 'SBIN260915901234',
    status: 'disbursed',
    disbursedDate: '2026-09-15',
    dualSignOffRequired: true,
    signOffAdmin1: 'superadmin@agrovercity.org',
    signOffAdmin2: 'director.women@agrovercity.in',
    justification: 'Procurement of spice grinding pulverizer and nitrogen-flushed pouch packing unit',
    createdAt: '2026-09-02T11:30:00Z',
    updatedAt: '2026-09-15T14:40:00Z'
  },
  {
    id: 'sub_03',
    shgId: 'shg_03',
    shgName: 'Ahilyabai Holkar Kisan Mahila Sangh',
    schemeName: 'NRLM Revolving Fund (RF) Grant for First-Generation Mahila Kisan',
    grantType: 'Revolving Fund (RF)',
    amountInr: 15000, // Below 50k
    bankReferenceUtr: 'HDFC260912389102',
    status: 'disbursed',
    disbursedDate: '2026-09-12',
    dualSignOffRequired: false,
    signOffAdmin1: 'superadmin@agrovercity.org',
    signOffAdmin2: null,
    justification: 'Standard revolving fund grant for SHG micro-credit rotation',
    createdAt: '2026-09-05T09:00:00Z',
    updatedAt: '2026-09-12T11:15:00Z'
  },
  {
    id: 'sub_04',
    shgId: 'shg_05',
    shgName: 'Bhagyalakshmi Mahila Sheti Bachat Gat',
    schemeName: 'Value-Addition Machinery Subsidy (Flour Mill & Dehydrator)',
    grantType: 'Machinery Subsidy',
    amountInr: 92000, // > ₹50,000 -> Dual sign-off required!
    bankReferenceUtr: 'SBLS260919102934',
    status: 'dual_signoff_pending',
    disbursedDate: null,
    dualSignOffRequired: true,
    signOffAdmin1: 'superadmin@agrovercity.org',
    signOffAdmin2: null,
    justification: '50% capital subsidy sanctioned by District Collectorate for millet processing unit',
    createdAt: '2026-09-17T14:00:00Z',
    updatedAt: '2026-09-19T10:30:00Z'
  },
  {
    id: 'sub_05',
    shgId: 'shg_07',
    shgName: 'Yashaswini Mahila Udhyog Bachat Gat',
    schemeName: 'NRLM Mission Shakti Interest Subvention',
    grantType: 'Interest Subvention',
    amountInr: 48000, // Below 50k
    bankReferenceUtr: 'MAHG260914881230',
    status: 'disbursed',
    disbursedDate: '2026-09-14',
    dualSignOffRequired: false,
    signOffAdmin1: 'superadmin@agrovercity.org',
    signOffAdmin2: null,
    justification: 'Half-yearly interest discount credit to bank account',
    createdAt: '2026-09-08T11:00:00Z',
    updatedAt: '2026-09-14T12:20:00Z'
  },
  {
    id: 'sub_06',
    shgId: 'shg_04',
    shgName: 'Kranti Jyoti Savitri Kisan Bachat Gat',
    schemeName: 'NRLM Revolving Fund (RF) Grant',
    grantType: 'Revolving Fund (RF)',
    amountInr: 15000,
    bankReferenceUtr: null,
    status: 'pending_approval',
    disbursedDate: null,
    dualSignOffRequired: false,
    signOffAdmin1: null,
    signOffAdmin2: null,
    justification: 'Awaiting primary SHG verification approval from desk officer',
    createdAt: '2026-09-16T15:00:00Z',
    updatedAt: '2026-09-16T15:00:00Z'
  }
]

export const mockWomenAuditLogs = [
  {
    id: 'aud_wom_101',
    adminUid: 'usr_admin_root',
    adminName: 'Super Admin',
    timestamp: '2026-09-19T10:30:00Z',
    ipAddress: '10.0.4.15',
    actionType: 'DUAL_SIGNOFF_SUBSIDY_DISBURSE',
    entityId: 'sub_04',
    entityName: 'Bhagyalakshmi Mahila Sheti Bachat Gat',
    collection: 'shg_subsidies',
    previousState: 'status: pending_approval',
    newState: 'status: dual_signoff_pending (Amount: INR 92,000)',
    reason: 'First admin authorized; pending second director sign-off per SOP dual compliance'
  },
  {
    id: 'aud_wom_102',
    adminUid: 'usr_admin_root',
    adminName: 'Super Admin',
    timestamp: '2026-09-18T14:20:00Z',
    ipAddress: '10.0.4.15',
    actionType: 'VERIFY_SHG_REGISTRATION',
    entityId: 'shg_01',
    entityName: 'Savitribai Phule Mahila Bachat Gat',
    collection: 'women_shgs',
    previousState: 'status: pending_verification',
    newState: 'status: verified',
    reason: 'Verified MSRLM registration docs, Bank of Maharashtra account, and Gram Panchayat resolution'
  },
  {
    id: 'aud_wom_103',
    adminUid: 'usr_admin_root',
    adminName: 'Super Admin',
    timestamp: '2026-09-17T16:15:00Z',
    ipAddress: '10.0.4.15',
    actionType: 'CURATE_STOREFRONT_PRODUCT',
    entityId: 'ent_prd_08',
    entityName: 'Amla Murabba (Wild Forest Honey)',
    collection: 'home_enterprises',
    previousState: 'status: pending_review',
    newState: 'status: changes_requested',
    reason: 'FSSAI license renewal and nutritional panel update required prior to marketplace activation'
  },
  {
    id: 'aud_wom_104',
    adminUid: 'usr_admin_root',
    adminName: 'Super Admin',
    timestamp: '2026-09-15T14:40:00Z',
    ipAddress: '10.0.4.15',
    actionType: 'DISBURSE_INTEREST_SUBVENTION',
    entityId: 'sub_02',
    entityName: 'Jijamata Mahila Krishi Vikas Bachat Gat',
    collection: 'shg_subsidies',
    previousState: 'status: approved',
    newState: 'status: disbursed (UTR: SBIN260915901234, INR 85,000)',
    reason: 'Direct account credit of CIF capital subsidy following co-admin authorization'
  }
]

export const mockWomenSummary = {
  totalActiveShgs: 8,
  totalMahilaKisanMembers: 115,
  cumulativeSavingsCorpusInr: 2625000,
  averageLoanRecoveryRatePct: 97.4,
  activeStorefrontProducts: 6,
  totalEnterpriseRevenueInr: 912850,
  pendingVerificationShgs: 2,
  flaggedAuditAlerts: 1
}
