import React from 'react';
import {
  X,
  FileText,
  ShieldCheck,
  Download,
  Printer,
  Calendar,
  IndianRupee,
  CheckCircle2
} from 'lucide-react';

export function LeaseAgreementModal({
  isOpen,
  onClose,
  agreement,
  lease,
  loading = false
}) {
  if (!isOpen || (!agreement && !lease)) return null;

  const clauses = agreement?.clauses || [
    `करार कालावधी: ${lease?.monthsTotal || 24} महिने (${lease?.startDate} ते ${lease?.endDate})`,
    `भाडे रक्कम: ₹${Number(lease?.monthlyRent || 0).toLocaleString('en-IN')} प्रति महिना, दरमहा ${lease?.rentDueDay || 5} तारखेस देय.`,
    `जमीन तपशील: सर्वे नं. ${lease?.surveyNo}, क्षेत्र ${lease?.areaAcres} एकर, जिल्हा ${lease?.district}`,
    `सुरक्षा ठेव (डिपॉझिट): ₹${Number(lease?.securityDeposit || 0).toLocaleString('en-IN')} — करार संपल्यानंतर ३० दिवसांत परतावा.`,
    `पीक हक्क: ${lease?.crop || 'सर्व प्रकारची पिके'} — भाडेकरूस कायदेशीर वहिवाटीचे पूर्ण हक्क राहतील.`,
    `वादनिवारण: वाद उद्भवल्यास ॲग्रोव्हर्सिटी सुपरॲडमिन व जिल्हा लवादाचा निर्णय उभयपक्षांवर बंधनकारक राहील.`
  ];

  const signatures = agreement?.signatures || [
    { party: 'landlord', name: lease?.landlordName || 'Landlord', signedAt: lease?.createdAt || new Date().toISOString() },
    { party: 'tenant', name: lease?.tenantName || 'Tenant', signedAt: lease?.createdAt || new Date().toISOString() }
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/40 backdrop-blur-xs p-4 overflow-y-auto">
      <div className="w-full max-w-2xl bg-white border border-emerald-100 rounded-2xl shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-150 my-8 flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="px-6 py-4 bg-emerald-50/50 border-b border-emerald-100 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-100 border border-emerald-200 text-emerald-700 flex items-center justify-center font-bold">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <span>Standardized Agricultural Land Lease Contract</span>
                <span className="text-[10px] font-mono bg-emerald-100 text-emerald-800 border border-emerald-200 px-1.5 py-0.5 rounded font-bold">
                  मराठी / Legal PDF
                </span>
              </h2>
              <p className="text-xs text-slate-500 mt-0.5">
                Agreement #{agreement?.id || `agr_${lease?.id}`} • Lease #{lease?.id}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 text-slate-400 hover:text-slate-700 rounded-lg hover:bg-emerald-100/50 transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Contract Viewer Document Body */}
        <div className="flex-1 overflow-y-auto p-6 space-y-5 text-xs text-slate-800">
          {/* Official Seal Banner */}
          <div className="border-2 border-emerald-700/30 rounded-xl p-4 bg-emerald-50/20 text-center space-y-1">
            <div className="text-[11px] font-bold text-emerald-900 tracking-wider uppercase font-mono">
              महाराष्ट्र शासन कृषी व महसूल प्रारूप मानके — शेतजमीन भाडेपट्टा करारपत्र
            </div>
            <div className="text-[10px] text-slate-500">
              Generated by Agrovercity Legal Protocol Engine · Template {agreement?.templateVersion || 'v2.4-MH-RERA'}
            </div>
          </div>

          {/* Parties Overview */}
          <div className="grid grid-cols-2 gap-4 bg-slate-50 p-4 rounded-xl border border-slate-200">
            <div>
              <div className="text-[10px] uppercase font-bold text-slate-500 font-mono">प्रथम पक्ष (जमीन मालक / Landlord)</div>
              <div className="text-sm font-bold text-slate-900 mt-1">{lease?.landlordName}</div>
              <div className="text-[11px] text-slate-600 font-mono mt-0.5">{lease?.landlordPhone}</div>
            </div>

            <div>
              <div className="text-[10px] uppercase font-bold text-slate-500 font-mono">द्वितीय पक्ष (भाडेकरू शेतकरी / Tenant)</div>
              <div className="text-sm font-bold text-slate-900 mt-1">{lease?.tenantName}</div>
              <div className="text-[11px] text-slate-600 font-mono mt-0.5">{lease?.tenantPhone}</div>
            </div>
          </div>

          {/* Core Terms */}
          <div className="grid grid-cols-3 gap-3 font-mono">
            <div className="bg-emerald-50/40 p-3 rounded-xl border border-emerald-100 text-center">
              <span className="text-[10px] text-slate-500 block">मासिक भाडे (Monthly Rent)</span>
              <span className="text-sm font-extrabold text-emerald-800">
                ₹{Number(lease?.monthlyRent || 0).toLocaleString('en-IN')}/mo
              </span>
            </div>
            <div className="bg-emerald-50/40 p-3 rounded-xl border border-emerald-100 text-center">
              <span className="text-[10px] text-slate-500 block">हमी अनामत ठेव (Deposit)</span>
              <span className="text-sm font-extrabold text-sky-800">
                ₹{Number(lease?.securityDeposit || 0).toLocaleString('en-IN')}
              </span>
            </div>
            <div className="bg-emerald-50/40 p-3 rounded-xl border border-emerald-100 text-center">
              <span className="text-[10px] text-slate-500 block">क्षेत्रफळ (Area Acres)</span>
              <span className="text-sm font-extrabold text-slate-900">
                {lease?.areaAcres} एकर ({lease?.district})
              </span>
            </div>
          </div>

          {/* Legal Clauses */}
          <div>
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-2">
              कायदेशीर अटी व शर्ती (Contract Clauses)
            </h3>
            <div className="space-y-2.5">
              {clauses.map((clause, idx) => (
                <div key={idx} className="flex items-start gap-2.5 p-2.5 rounded-lg bg-slate-50 border border-slate-200/80">
                  <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-800 font-bold font-mono text-[10px] flex items-center justify-center shrink-0 mt-0.5">
                    {idx + 1}
                  </span>
                  <span className="leading-relaxed text-slate-700 font-medium">{clause}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Dual Digital Aadhaar e-Signatures */}
          <div className="pt-3 border-t border-slate-200">
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-2">
              डिजिटल स्वाक्षरी प्रमाणीकरण (Digital e-Sign Records)
            </h3>
            <div className="grid grid-cols-2 gap-3">
              {signatures.map((sig, idx) => (
                <div key={idx} className="p-3 rounded-xl border border-emerald-200 bg-emerald-50/30 space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] uppercase font-bold text-emerald-800 font-mono">
                      {sig.party === 'landlord' ? 'जमीन मालक स्वाक्षरी' : 'भाडेकरू स्वाक्षरी'}
                    </span>
                    <span className="flex items-center gap-1 text-[10px] font-bold text-emerald-700 bg-emerald-100 px-1.5 py-0.5 rounded-full">
                      <CheckCircle2 className="w-3 h-3" /> UIDAI e-Sign Verified
                    </span>
                  </div>
                  <div className="font-bold text-slate-900 text-xs">{sig.name}</div>
                  <div className="text-[10px] text-slate-500 font-mono">
                    Signed: {new Date(sig.signedAt).toLocaleString()}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2 text-[11px] text-slate-500 font-mono">
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
            <span>Digital stamp duty legal copy stored in vault</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="px-3 py-1.5 bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 rounded-xl text-xs font-bold transition-colors flex items-center gap-1.5 shadow-xs"
            >
              <Printer className="w-3.5 h-3.5 text-slate-500" />
              <span>Print</span>
            </button>

            <button
              onClick={onClose}
              className="px-4 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-xl text-xs font-bold transition-all shadow-xs"
            >
              Close Inspector
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
